# Service for the application
apiVersion: v1
kind: Service
metadata:
  name: go-web-app-srihari
  labels:
    app: go-web-app-srihari 
spec:
  ports:
  - port: 80
    targetport: 8080
    protocol: TCP
  selector:
    app: go-web-app-srihari
  type: ClusterIP
   